#!/usr/bin/env python
"""
Copyright 2015 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

class InputFile:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            
            'id': 'str',
            
            
            'type': 'str',
            
            
            'source': 'str',
            
            
            'filename': 'str',
            
            
            'size': 'int',
            
            
            'created_at': 'DateTime',
            
            
            'modified_at': 'DateTime'
            
        }


        
        #Unique identifier for the file.
        
        self.id = None # str
        
        #How the file has been generated.
        
        self.type = None # str
        
        #The source of the file to be used that can be either, an external url. An identifier for an uploaded file to the server or an identifier for another job.
        
        self.source = None # str
        
        #Filename of the file.
        
        self.filename = None # str
        
        #Size of the file in bytes.
        
        self.size = None # int
        
        #Date and time when the job was created.
        
        self.created_at = None # DateTime
        
        #Date and time when the job was last modified.
        
        self.modified_at = None # DateTime
        
