#!/usr/bin/env python
"""
Copyright 2015 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

class Job:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            
            'id': 'str',
            
            
            'token': 'str',
            
            
            'type': 'str',
            
            
            'status': 'Status',
            
            
            'process': 'bool',
            
            
            'conversion': 'list[Conversion]',
            
            
            'input': 'list[InputFile]',
            
            
            'callback': 'str',
            
            
            'server': 'str',
            
            
            'created_at': 'DateTime',
            
            
            'modified_at': 'DateTime'
            
        }


        
        #Unique identifier for the job.
        
        self.id = None # str
        
        #Token to identify client allowed to run the job.
        
        self.token = None # str
        
        #Type of the job created.
        
        self.type = None # str
        
        #Current status for the job
        
        self.status = None # Status
        
        #Determine if the job must be processed as soon as it is ready.
        
        self.process = None # bool
        
        #Type of conversion or conversions to be carried out.
        
        self.conversion = None # list[Conversion]
        
        #Source or sources of the files to be converted.
        
        self.input = None # list[InputFile]
        
        #Callback url to the the status updates
        
        self.callback = None # str
        
        #Server assigned for file uploads and downloads
        
        self.server = None # str
        
        #Date and time when the job was created.
        
        self.created_at = None # DateTime
        
        #Date and time when the job was last modified.
        
        self.modified_at = None # DateTime
        
